seeder:
  file: ./seeder/seeder.rb
  disabled: false
parsers:
  - file: ./parsers/job_list.rb
    page_type: job_list
    disabled: false
  - file: ./parsers/job_detail.rb
    page_type: job_detail
    disabled: false
exporters:
  - file: ./exporters/job_listing10_json.yaml
    disabled: false
  - file: ./exporters/job_listing_json.yaml
    disabled: false
  - file: ./exporters/job_listing_csv.yaml
    disabled: false