seeder:
  file: ./seeder/seeder.rb
  disabled: true
parsers:
  - file: ./parsers/job_list.rb
    page_type: job_list
    disabled: true
  - file: ./parsers/job_detail.rb
    page_type: job_detail
    disabled: true
exporters:
  - file: ./exporters/job_listing10_json.yaml
    disabled: true
  - file: ./exporters/job_listing_json.yaml
    disabled: true
  - file: ./exporters/job_listing_csv.yaml
    disabled: true
