seeder:
  file: ./seeder/seeder.rb
  disabled: false
parsers:
  - file: ./parsers/job_list.rb
    page_type: job_list
    disabled: false
  - file: ./parsers/job_detail.rb
    page_type: job_detail
    disabled: false